server:
  port: 8082

spring:
  application:
    name: product-consumer-service
  grpc:
    client:
      product-producer:
        address: localhost:9090
        negotiation-type: plaintext
      enabled: true
  main:
    banner-mode: off
logging:
  level:
    de.hdi: DEBUG
    io.grpc: DEBUG
    root: INFO